backend:
  name: github
  repo: xuehan2007/Firefly
  branch: master
  base_url: ""

media_folder: "public/images"
public_folder: "/images"

editor:
  preview: true

collections:
  - name: "posts"
    label: "文章"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "published", widget: "datetime" }
      - { label: "摘要", name: "description", widget: "text" }
      - { label: "封面图", name: "image", widget: "image", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "category", widget: "string", required: false }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "置顶", name: "pinned", widget: "boolean", default: false }
      - { label: "正文", name: "body", widget: "markdown" }
